### ISSUE TITLE
Can not use the gem with npm package

### ISSUE THREAD

**Issue by JuanVqz** [josefarias/hotwire_combobox#115]
**Describe the bug**

I wanted to try the gem, followed the [readme](https://github.com/josefarias/hotwire_combobox?tab=readme-ov-file#js-bundling-esbuild-rollup-etc), and implemented it  easily (you can see the PR linked below)

PR: https://github.com/JuanVqz/doctors/pull/521

**To Reproduce**
1. Install the gem and npm package
2. Run the rails server and you should see the error.  

**Expected behavior**
Be able to use the gem

**Screenshots**
![hw-combobox](https://github.com/josefarias/hotwire_combobox/assets/7331511/bcf292db-4651-42b2-be9e-6b6c389fd72c)

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - OS Chrome

**Additional context**
I solved it with a temporal workaround, renaming the file from `"app/assets/javascripts/hotwire_combobox.esm.js",` to `"app/assets/javascripts/hotwire_combobox.umd.js",`.

![hw-combobox-2](https://github.com/josefarias/hotwire_combobox/assets/7331511/9d1cca20-a5dc-4a05-9b10-8ae27db8e59d)

I'll continue debugging, thanks!

**Comment by JuanVqz** [comment]
A possible solution is to use umd for both cases.

```json
  "module": "app/assets/javascripts/hotwire_combobox.umd.js",
  "main": "app/assets/javascripts/hotwire_combobox.umd.js",
```

I can open a PR if wanted.

**Comment by josefarias** [comment]
Oh, strange. Seems like the esm build is missing from the published package. I'll take a look. Thanks!

**Comment by josefarias** [comment]
I think this might do the trick but we'll have to wait until the next version is published to npm to know for sure

**Comment by josefarias** [comment]
@JuanVqz should be good to go per https://www.npmjs.com/package/@josefarias/hotwire_combobox?activeTab=code!

Closing for now but let me know if the issue persists after updating to version 0.2.0, please

**Comment by JuanVqz** [comment]
@josefarias, Thank you for fixing and releasing it really quick, was faster than I thought, Saludos!

**Comment by JuanVqz** [comment]
@josefarias the fix works like a charm, thanks! :shipit:

**Comment by josefarias** [comment]
Great to hear! Thanks for reporting back 🫡
