### ISSUE TITLE
Include link to the repo on docs page

### ISSUE THREAD

**Issue by morgoth** [josefarias/hotwire_combobox#12]
It would be very useful to have link to this GH repo on the https://hotwirecombobox.com/ page, so the visitor has an easy way to reach it.

Looks nice! Thank you.

**Comment by morgoth** [comment]
ah, it's already there.
I was looking for it at the footer or header after reading the intro...

**Comment by josefarias** [comment]
Right! It's there, but should probably be more prominent. Other libraries have a callout in the top right corner. I'll consider adding a more prominent link. Thanks!
