### ISSUE TITLE
`include_blank: true` renders `true` into the combobox

### ISSUE THREAD

**Issue by searls** [josefarias/hotwire_combobox#125]
**Describe the bug**

The `include_blank:` option wants a hash or text to fill the "blank" option, but an actually blank string option won't be [present?](https://github.com/josefarias/hotwire_combobox/blob/068cbca5bc7ccfe1e841b7258a165cfb3a7120ca/app/presenters/hotwire_combobox/listbox/item.rb#L18) and thus fail to register. And setting it to `true` (as one would for a select box) renders the literal `true`

**To Reproduce**

```erb
<!-- Renders "true" -->
<%= f.combobox :thing_id, Thing.all, include_blank: true %>

<!-- No blank, because not present? -->
<%= f.combobox :thing_id, Thing.all, include_blank: "" %>

<!-- Renders an invisible non-breaking space character successfully -->
<%= f.combobox :thing_id, Thing.all, include_blank: "&nbsp;".html_safe %>
```

**Screenshots**

![screenshot-2024-03-29-08h10m22s](https://github.com/josefarias/hotwire_combobox/assets/79303/d395f4b5-2e5f-4418-ba6f-98bc7fc31d24)
![screenshot-2024-03-29-08h10m31s](https://github.com/josefarias/hotwire_combobox/assets/79303/33e5febf-84b3-4295-a275-909903bd9d3f)

**Additional context**

My advice would be to add a final else to this that just renders a string. Something like this maybe?

```ruby
    def extract_blank_display_and_content
      if include_blank.is_a? Hash
        text = include_blank.delete(:text)

        [ text, render_content(render_opts: include_blank, object: text, attrs: { display: text, value: "" }) ]
      elsif include_blank.is_a?(String)
        [ include_blank, include_blank ]
      else
        [ "", nil ]
      end
    end
```

**Comment by josefarias** [comment]
Thanks Justin! Fixed in https://github.com/josefarias/hotwire_combobox/pull/130
