### ISSUE TITLE
Clear button flexibility

### ISSUE THREAD

**Issue by dixpac** [josefarias/hotwire_combobox#141]
This is not a bug, just an idea.

Currently clear button(x) and carrot(or custom icon) are interchangeable

https://github.com/josefarias/hotwire_combobox/assets/7427365/e681c314-3cf8-404f-aa30-803888a46124

While this looks clean I think it has drawbacks, for example what if I want to have search magnifier icon as a prefix and clear button at the end, something like this:

<img width="566" alt="Screenshot 2024-04-08 at 13 37 30" src="https://github.com/josefarias/hotwire_combobox/assets/7427365/b1cd67a1-d546-4674-8eb7-443ca7909586">

----

<img width="593" alt="Screenshot 2024-04-08 at 13 37 43" src="https://github.com/josefarias/hotwire_combobox/assets/7427365/80f2024b-34f4-47d6-80ab-481055f141f7">

I feel like ti would be more flexible to have these 2 buttons/actions as a separate "concept".

Here is how this looks on [shoelace select component](https://shoelace.style/components/select/)
<img width="803" alt="Screenshot 2024-04-08 at 13 40 53" src="https://github.com/josefarias/hotwire_combobox/assets/7427365/e5d8161f-b9ba-4ee6-9bed-1cf6e48fce07">

**Comment by josefarias** [comment]
Hey @dixpac! Good idea. I'd be open to a PR for this as long as the code is concise and simple.

Let's move this to the discussions forum, though. To keep issues constrained to bugs. Thanks!

**Comment by dixpac** [comment]
Ahhh sorry wasn't aware about the forum :)

Great, I'll give it a shot and see where it goes

**Comment by josefarias** [comment]
No worries! Not all repos use that GH feature.

Awesome! Thanks Dino
