### ISSUE TITLE
Retrieving paginated results seems to arbitrarily stop appending to the results list

### ISSUE THREAD

**Issue by aseroff** [josefarias/hotwire_combobox#156]
# Bug description
Paginated async results seem to stop loading pages after an arbitrary amount of time

## To Reproduce
1. Have an endpoint that has 5+ pages
2. Scroll down to load more results. After 3 or 4 pages, no more results are appended

## Expected behavior
Results are appended until the final page is reached

## Code
```
# app/views/library/textbooks/index.turbostream.haml
= async_combobox_options @textbooks, render_in: { partial: 'library/textbooks/search_result' }, next_page: (@pagination_info[:page] < @pagination_info[:total_pages] ? (@pagination_info[:page] + 1) : nil)
```

### HotwireCombobox info
 - Gem version: v0.1.43

### Desktop info (if applicable)
 - OS: Mac
 - Browser: Chromium-based

## Additional context
Confirmed that it wasn't my pagination logic by replacing `@pagination_info[:page] < @pagination_info[:total_pages]` with `true`, problem persisted.

**Comment by josefarias** [comment]
Hey @aseroff, this was reported once before by @dixpac but I couldn't reproduce.

I'm going to need a link to a rails app I can run locally and debug in order to fix this.

Alternatively, did you ever figure this one out @dixpac?

**Comment by aseroff** [comment]
Reassuring that it's not just me. I can point you to https://staging.open.umn.edu/textbooks for a live example, but I'll have to get back to you on a cloneable repo.

**Comment by josefarias** [comment]
@aseroff thanks for the live example, that's very helpful!

I see what's happening. The pagination trigger at the bottom of the options list isn't triggering because Turbo's intersection observer doesn't consider it visible. Interesting how this doesn't happen every time. Might be an artifact of the custom styles, or a browser-specific issue.

The fix should be simple — just give the trigger a small height so it's guaranteed to be visible. I'll get to work on that.

Thanks!

**Comment by josefarias** [comment]
@aseroff I've just released v0.2.4

Could I get you to update the gem please (remember to also update the JS package if you're not using importmaps) and let me know if it's working now, please? Thanks! Closing for now but will reopen if not solved.

**Comment by josefarias** [comment]
Ope, make that v0.2.5 sorry (will release shortly) — missed this: https://github.com/josefarias/hotwire_combobox/pull/158

**Comment by aseroff** [comment]
Bumped and confirmed the fix. Thank you!

**Comment by dixpac** [comment]
@josefarias I can confirm that [this](https://github.com/josefarias/hotwire_combobox/pull/157) fixes issue I've been seeing 👍
