### ISSUE TITLE
Searching async combobox jumps to top when loading more results

### ISSUE THREAD

**Issue by ILiuz** [josefarias/hotwire_combobox#159]
# Bug description
Searching in an async combobox and then scrolling to the pagination threshold, will result in a jump to the top of the list, and not keep your current position.

## To Reproduce
1. Open an async combobox and search for something that will give paginated results
2. Scroll down the list until you get to the pagination threshold
3. Notice that you will jump to top as you cross the pagination threshold

## Expected behavior
On step 3, you should keep your position in the list

### HotwireCombobox info
 - Gem version: v0.2.5
 - NPM version: v0.2.5

### Desktop info
 - OS: macOS Sonoma 14.4.1
 - Browser: Chrome 
 - Browser Version: 124.0.6367.119 (Official Build) (arm64)

## Additional context
I do not believe this is related to the wrap-around scrolling, but an issue with how new lazy-loaded elements are added to the list.

The file [_pagination.html](https://github.com/josefarias/hotwire_combobox/blob/main/app/views/hotwire_combobox/_pagination.html.erb) is responsible for producing the element that will trigger the lazy loading:
```erb
<%# locals: (for_id:, src:) -%>

<%= tag.li id: hw_pagination_frame_wrapper_id(for_id), class: "hw_combobox__pagination__wrapper",
      data: { hw_combobox_target: "endOfOptionsStream", input_type: params[:input_type] },
      aria: { hidden: true } do %>
  <%= turbo_frame_tag hw_pagination_frame_id(for_id), src: src, loading: :lazy %>
<% end %>
```
When you search the combobox, _input_type_ will be set to **insertText** to make sure you jump to the top, for the most relevant item. Since this element is inserted with the same data-attribute every time you hit the pagination threshold in the list (unless you have done some other action, like backspace delete text), it will keep jumping you back to the top as you scroll down the list of options and lazy load more results.

I believe _input_type_ should only be set to **insertText** on the first request after the user has entered text, and not for subsequent lazy-loaded requests, but I am not sure how to do that, or what the ramifications would be, so I filed a bug report instead of a pull request.

**Comment by josefarias** [comment]
Thanks @ILiuz. v0.2.5 was just released yesterday. Just to help narrow things down, did you experience this before that release? (Assuming you've been using the combobox for a while, maybe you haven't)

**Comment by josefarias** [comment]
Running a git bisect, seems like this was introduced here: https://github.com/josefarias/hotwire_combobox/commit/0660671f4669c3fb38eada3da34872bf04bee3a8

Taking a look now.

**Comment by ILiuz** [comment]
It seems like you already found the relevant commit, which fits with my experience. I experienced the issue with v0.2.3 and upgraded to v0.2.5 just to make sure it wasn’t already resolved. Thank you for taking a look!

**Comment by josefarias** [comment]
@ILiuz just pushed v0.3.0. Should be fixed in that version. Thanks!
