### ISSUE TITLE
Importmaps are pinning and preloading both UMD and ESM builds (and ~25 other files)

### ISSUE THREAD

**Issue by searls** [josefarias/hotwire_combobox#177]
I'm trying to clear these warnings from my browser while debugging my app, because only the admin section of my site currently uses hotwire_combobox:

```
The resource /assets/hotwire_combobox.esm-3cc9ba76.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
The resource /assets/hotwire_combobox.umd-c0b89259.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
```

If you're using importmaps, the [importmap.rb](https://github.com/josefarias/hotwire_combobox/blob/main/config/hw_importmap.rb):

```ruby
pin_all_from File.expand_path("../app/assets/javascripts", __dir__)
```

Will pin and (apparently?) preload both of these files (they aren't checked into the repo, as they're generated):

```
app/assets/javascripts/hotwire_combobox.esm.js
app/assets/javascripts/hotwire_combobox.umd.js
```

I guess there are two issues here:

1. Is the UMD build _ever_ appropriate to pin or preload for importmaps users? Since importmaps depends on ESM, I would hazard a guess no? In that case it might be more appropriate to rewrite `hw_importmap.rb` to only pin the ESM build
2. Would it be possible to make the preload-or-not config exposed to end users in a reasonable way? This feels like it may be a limitation of importmap-rails, given that [Mission Control has a similar issue](https://github.com/rails/mission_control-jobs/issues/132)

Additionally, by using `pin_all_from`, individual `modulepreload` links are generated for each and every JavaScript file in the project, which is probably not what you want

```html
<link rel="modulepreload" href="/assets/controllers/hw_combobox_controller-7808ba7e.js">
<link rel="modulepreload" href="/assets/hotwire_combobox.esm-3cc9ba76.js">
<link rel="modulepreload" href="/assets/hotwire_combobox.umd-c0b89259.js">
<link rel="modulepreload" href="/assets/hw_combobox/helpers-8ec22533.js">
<link rel="modulepreload" href="/assets/hw_combobox/models/combobox-1aae564d.js">
<link rel="modulepreload" href="/assets/hw_combobox/models/combobox/actors-4cfc477f.js">
<link rel="modulepreload" href="/assets/hw_combobox/models/combobox/announcements-c9445511.js">
<link rel="modulepreload" href="/assets/hw_combobox/models/combobox/async_loading-dfdc40ad.js">
<link rel="modulepreload" href="/assets/hw_combobox/models/combobox/autocomplete-60883f3d.js">
<link rel="modulepreload" href="/assets/hw_combobox/models/combobox/base-911febd6.js">
<link rel="modulepreload" href="/assets/hw_combobox/models/combobox/dialog-50e693d4.js">
<link rel="modulepreload" href="/assets/hw_combobox/models/combobox/events-b35491be.js">
<link rel="modulepreload" href="/assets/hw_combobox/models/combobox/filtering-d226165c.js">
<link rel="modulepreload" href="/assets/hw_combobox/models/combobox/form_field-6e867c92.js">
<link rel="modulepreload" href="/assets/hw_combobox/models/combobox/multiselect-4e9dc1e7.js">
<link rel="modulepreload" href="/assets/hw_combobox/models/combobox/navigation-38901208.js">
<link rel="modulepreload" href="/assets/hw_combobox/models/combobox/new_options-28b5f452.js">
<link rel="modulepreload" href="/assets/hw_combobox/models/combobox/options-f024585b.js">
<link rel="modulepreload" href="/assets/hw_combobox/models/combobox/selection-06963375.js">
<link rel="modulepreload" href="/assets/hw_combobox/models/combobox/toggle-39497388.js">
<link rel="modulepreload" href="/assets/hw_combobox/models/combobox/validity-d73d5ad4.js">
<link rel="modulepreload" href="/assets/hw_combobox/vendor/bodyScrollLock-e4b6c83f.js">
<link rel="modulepreload" href="/assets/hw_combobox/vendor/requestjs-e9b49506.js">
```

**Comment by searls** [comment]
I forked the repo to try finding a workaround, and was able to get it to load by changing hw_importmap.rb in each of these ways:

```ruby
pin "hotwire_combobox", to: "hotwire_combobox.esm.js", preload: true
```

```ruby
pin "hotwire_combobox", to: "controllers/hw_combobox_controller.js", preload: true
pin_all_from HotwireCombobox::Engine.root.join("app/assets/javascripts/hw_combobox"), under: "hw_combobox", to: "hw_combobox"
```

This also required me to have an `import 'hotwire_combobox'` somewhere in my application.js for them to load, though.

Additionally, (and more importantly), **the actual hotwire combobox functionality didn't work**. I'm unsure why not and couldn't figure it out

**Comment by josefarias** [comment]
Thanks for raising this and trying to find a workaround.

Yeah, this is a remnant from first spiking on the library and trying a spray approach. I'll have to take a look and see what we need and don't need. UMD is probably fine to drop, and I'd expect ESM to be able to stand on its own, since that's what's published on npm for use in non-importmap apps. But that's evidently not working so something's up.

I'll keep this open while I (or someone else) take a look.

**Comment by searls** [comment]
Hi @josefarias, great to see you last week!

I'd really love help solving this. Without a workaround, I'm afraid that ~20% of my app's import map entries are tied to HW Combobox

**Comment by josefarias** [comment]
Great to see you too @searls!

This is on my radar as part of https://github.com/josefarias/hotwire_combobox/discussions/200, and we'll get to it. But if I'm completely honest, I'm more focused on finalizing existing features so we can ship v1.0.

> I'm afraid that ~20% of my app's import map entries are tied to HW Combobox

I can see why loading a single file is nicer than however many we're currently loading. But this is intended to work with HTTP/2, so the (temporary) overhead should be quite small, unless I'm missing something. Is this causing an active problem in your app?

**Comment by searls** [comment]
@josefarias the issue isn't the number of files per se, it's that in addition to loading each individual file it is *ALSO* loading the entire ESM bundle and *ALSO* loading the entire UMD bundle, which means that every user of the app is loading hotwire combobox 3 times

**Comment by josefarias** [comment]
@searls ah! I was under the assumption that the UMD and ESM bundles weren't actually there. But they are! Because upon releasing we just happen to push to npm first, which creates those bundles:
https://github.com/josefarias/combobox/blob/1b3bc1675beecdd6f6cede27cff61453ecd0b0d5/bin/release#L19-L20

Yeah, I'll bump up the priority on this, that's totally unnecessary.

In the meantime, the files should be being downloaded in parallel with HTTP/2, so I think at worst this is an unnecessary hit on the server but not noticeable to the user. Is that right? Just trying to assess the impact. Working on this today.

**Comment by searls** [comment]
thanks for the quick reply @josefarias! Yeah, I think if you're using importmaps and Rails you're gonna discover in a hurry if you don't have a good caching strategy, CDN, and HTTP2/3 in place sooner or later, so I think if this does harm anyone's app performance it'll hopefully prompt them to address those issues.

More broadly, I think as a matter of general dependency management, it's easier for consumers of libraries to juggle third party code when it's delivered in a single atomical _thing_, which is why we started concatenating, minifying, and gzipping JavaScript libraries in the long long ago, pre-npm days. Any developer or user or auditor could point to that file and know it's version X of whatever dependency and rely on it also hasing to the same value.

That said, I don't think it's an urgent thing that should block you from calling 1.0, just something to consider moving forward in how you distribute this and other libraries. As one of the best Rails-oriented Stimulus libraries, how you choose to distribute hotwire_combobox will help set the precedent for how other maintainers will write their own gems that include JS

**Comment by josefarias** [comment]
@searls thanks for the ping here, I think I've managed to find a fix that just works. Could I get you to point your gem to this branch and report back? https://github.com/josefarias/hotwire_combobox/pull/209

Thanks!

**Comment by searls** [comment]
Only reference left in my app is the right one!

```html
<link rel="modulepreload" href="/assets/hotwire_combobox.esm-c6b5cc75.js">
```

LGTM!
