### ISSUE TITLE
Dispatch Stimulus events

### ISSUE THREAD

**Issue by ascruggs** [josefarias/hotwire_combobox#181]
This project is incredible. Thank you for tackling such a tough UX problem.  

As I am using it, I found myself really wanting to hook in to some type of callback system.  That said, since it is all stimulus based, it would be awesome if you called [dispatch](https://stimulus.hotwired.dev/reference/controllers#cross-controller-coordination-with-events) when different events occurred.

FWIW, currently, I am having to use a Mutation Observer.

**Comment by ILiuz** [comment]
You should be able to hook in to _hw-combobox:preselection_, _hw-combobox:selection_, and _hw-combobox:removal_. Relevant [source code](https://github.com/josefarias/hotwire_combobox/blob/f700dadeaebc66fd1c8417649720ea62b29fe30b/app/assets/javascripts/hw_combobox/models/combobox/events.js)

**Comment by ascruggs** [comment]
Amazing!  Worked perfectly. Thank you so much.
For such a new project, it is remarkably well thought through.

**Comment by Michoels** [comment]
For future readers, the exact syntax is:

```erb
<!--In your view somewhere -->
<div data-controller='example' data-action='hw-combobox:selection->example#handleEvent'>
  <%= f.combobox … %>
</div>
```

```javascript
// Example Stimulus controller `example_controller.js`
import { Controller } from "@hotwired/stimulus";

export default class extends Controller {
  handleEvent(event) {
    const selectedValue = event.detail.value; // This will be the `value` of the selected option
  }
}
```
