### ISSUE TITLE
Multiselect values as array

### ISSUE THREAD

**Issue by Alejandro-Bernal-M** [josefarias/hotwire_combobox#202]
Hi! First of all, thank you for this amazing tool.
I have implemented the multi-select combobox inside a ransack search (skills_name_in) but it expects an array. Is it possible to configure the multi-select to send the array of values instead of a string?

**Comment by josefarias** [comment]
Hey @Alejandro-Bernal-M, glad to know the library's been useful

You should be able to convert the string into an array via e.g. `params[:values].split(",")`. Let me know if that doesn't work for you, closing for now. But happy to reopen.

**Comment by Alejandro-Bernal-M** [comment]
Thank you for the fast response, at this moment I'm working with that approach but I wanted to know if there was a way to avoid processing the parameters. I will keep that approach then. Thank you again

**Comment by janpeterka** [comment]
I also think this would be nice to have natively, if possible. It would make the experience more seamless, without the need to always remember to add this conversion in controller on adding combobox.
