### ISSUE TITLE
isolated stacking context obscures active listbox if they overlap

### ISSUE THREAD

**Issue by metkat** [josefarias/hotwire_combobox#21]
https://github.com/josefarias/hotwire_combobox/blame/1c6afc13e7bd5809df5a80e89ce26e9ae678eada/app/assets/stylesheets/hotwire_combobox.css#L50

Having each combobox in an isolated stacking context means that if combobox A is a line or two above combobox B, clicking to reveal the listbox for A will result in inactive B obscuring some of the options in the listbox for A. My workaround is adding `.hw-combobox {
	isolation: auto;
}
` to my site CSS, but is the isolate necessary?

**Comment by josefarias** [comment]
Hm I think the isolation might be a remnant from an earlier implementation. I'd welcome a PR to remove it if you find it's not needed.

Can also look into it myself soon.
