### ISSUE TITLE
Overriding attributes on hidden field

### ISSUE THREAD

**Issue by SebastianSzturo** [josefarias/hotwire_combobox#24]
I am trying to submit a form whenever the value of the combobox changes. My first approach would be to add an `onchange` listener to the input, but it seems like only the value of the hidden input changes when selecting a different value.

My naive approach, that isn't working:

```
<%= form.combobox :category_id, Transaction::Category.all, input: { onchange: "this.form.requestSubmit()" } %>
```

I believe being able to customize the attributes of the hidden field would allow for that:

```
<%= form.combobox :category_id, Transaction::Category.all, hidden_input: { onchange: "this.form.requestSubmit()" } %>
```

Is there are more obvious different approach that I am missing? If not I have a branch to add the `hidden_input` kwarg to `HotwireCombobox::Component` to override hidden input attributes that I am happy to open as a PR.

**Comment by josefarias** [comment]
Interesting use case! I think supporting this makes sense.

I don't _think_ adding onchange to the hidden input would do what you want because I believe change events for inputs only fire after losing focus — which the hidden input never had. I might be wrong though.

One thing we could do is emit a custom event in `._commitSelection()` and/or in `._ensureSelection()`. I'd have to do some thinking on which would be better.

Then you're free to listen for that event e.g. in a stimulus controller and auto-submit the form. Although I'd suggest you look into the accessibility implications of that.

**Comment by SebastianSzturo** [comment]
You are right, `onchange` doesn't work here. I was able to get it working with my branch by adding a stimulus controller to the hidden field:

```javascript
import { Controller } from "@hotwired/stimulus"

export default class extends Controller {
  connect() {
    this.observer = new MutationObserver(mutations => {
      mutations.forEach(mutation => {
        if (mutation.type === "attributes" && mutation.attributeName === "value") {
          this.submitForm();
        }
      });
    });

    this.observe();
  }

  observe() {
    this.observer.observe(this.element, {
      attributes: true 
    });
  }

  submitForm() {
    this.element.form.requestSubmit();
  }

  disconnect() {
    this.observer.disconnect();
  }
}
```

I guess either having an event api or allowing custom stimulus controllers on the hidden and/or regular input would solve this problem.

**Comment by mackross** [comment]
I also tried adding ` onchange: "this.form.requestSubmit()"` hoping it would work. Given that it's the obvious API maybe we can make onchange work as expected?

**Comment by josefarias** [comment]
I'm not sure it's obvious to everyone. There's more than one input state to consider here. Mainly the combobox input and the hidden input. And then there's the arguably less prominent dialog input to consider.

To someone who's familiar with the implementation, a custom onchange implementation might be confusing.

I need to do some more thinking about this. But we'll definitely have a way to hook into selection. I'm thinking it will most likely be through a custom event.

Open to input one way or the other.

**Comment by MarcusRiemer** [comment]
I will have a similar use case and so far use https://www.stimulus-components.com/docs/stimulus-rails-autosave for that. It would be great if the interface offered here could feed into that stimulus rails autosave. From my understanding a custom event would allow that.

**Comment by josefarias** [comment]
Let's continue this conversation in https://github.com/josefarias/hotwire_combobox/discussions/71

**Comment by joyoy96** [comment]
I need this too since I want to change the `form_attributes` of the hidden fields

**Comment by josefarias** [comment]
It's supported! https://github.com/josefarias/hotwire_combobox/discussions/134#discussioncomment-8965235
