### ISSUE TITLE
Bug Report: A prefilled html combobox

### ISSUE THREAD

**Issue by pedrocarmona** [josefarias/hotwire_combobox#41]
Hi @josefarias,

I have encountered a bug while using hotwire_combobox with html in a prefilled form. 

**Description of the Bug**
Render a form, with html options, the input shows actual html tags in the selected value.

![actual](https://github.com/josefarias/hotwire_combobox/assets/2815199/023d4741-22f3-41f2-9c25-74edbcd55dbb)

**Expected Results**
I expect the value to be rendered not the html with the value.

![expected](https://github.com/josefarias/hotwire_combobox/assets/2815199/18e46a5a-d610-483d-b85e-82194b0a411a)

**Steps to Reproduce the Bug**

1. Create a record with an association
2. Create a form for the record and a combobox with render_in option and an html partial
3. Render the view

I have also created a [Hotwire Combobox Docs Diff](https://github.com/josefarias/hotwire_combobox_docs/compare/main...pedrocarmona:hotwire_combobox_docs:report/html-prefilled-render-issue)

**Demo**

https://github.com/josefarias/hotwire_combobox/assets/2815199/006ee325-d9b2-4ddc-a2b4-0f7256ebee3e

Thank you,
Pedro

**Comment by josefarias** [comment]
Hey @pedrocarmona, great catch! Thanks for a well written report, too.

This should be fixed in https://github.com/josefarias/hotwire_combobox/pull/43. If you get a sec, could I get you to point your gem to that branch and confirm the fix, please?

Thanks!

**Comment by pedrocarmona** [comment]
Hi @josefarias ,

Thank you for fixing, I confirmed it was fixed, and now I see the expected value should be `Amelie`. 
(This its also the favorite_movie in the user fixture).

<img width="793" alt="Screenshot 2024-02-29 at 00 07 28" src="https://github.com/josefarias/hotwire_combobox/assets/2815199/9d12c9e8-b7ce-4f1e-b7d9-4a3ac640a9d4">

I can't take all the credit, Generative AI did help templating the bug report :)

Thank you very much again!

**Comment by josefarias** [comment]
> Generative AI did help templating the bug report 

Nice!

Good to hear. I'll merge now and hope to be cutting a new release soon.

**Comment by jonyoi** [comment]
hey could you please advise how your pre-filled state has a down arrow instead of "x" mark? I am using pre-filled states and they all have an "x" mark instead of a down arrow and being new to rails I am unable to figure this out.

Thanks a bunch in advance
