### ISSUE TITLE
Grouping options

### ISSUE THREAD

**Issue by edwinv** [josefarias/hotwire_combobox#87]
We'd love to replace our internal combobox/select component with the Hotwire Combobox component. Our current implementation relies on generating JS in the frontend, which means its not compatible with Turbo 8 morphing.

One of the features we currently need and is missing from this component is grouping. Sometimes we have long lists of options that are grouped. We use `optgroup` in our HTML and render specific headers before each group. When we filter the list, the groups always stay visible when they contain a matching option.

Full list:
![CleanShot 2024-03-10 at 15 59 56@2x](https://github.com/josefarias/hotwire_combobox/assets/563294/2b60bf7f-6993-4912-a1d5-cf3ce9718e04)

Filtered list:

![CleanShot 2024-03-10 at 16 00 40@2x](https://github.com/josefarias/hotwire_combobox/assets/563294/892c3b7d-e775-4720-bca6-b8064633d5fb)

Are there plans to add this feature to this component?

**Comment by josefarias** [comment]
Let's move this conversation to a GH discussion: https://github.com/josefarias/hotwire_combobox/discussions/88
