### ISSUE TITLE
Order of collection affects selection ability

### ISSUE THREAD

**Issue by aroth** [josefarias/hotwire_combobox#94]
Option "A" cannot be selected (left):
```
  <%= form.combobox(
    :supervisor_idx,
    ["A1", "A", "A2", "A3"]
  ) %>
```

All options are selectable (right):
```
  <%= form.combobox(
    :supervisor_idy,
    ["A", "A1", "A2", "A3"]
  ) %>
```
![order](https://github.com/josefarias/hotwire_combobox/assets/542/3f56aa26-f9d2-4eeb-85b0-3055ab35075b)

**Comment by josefarias** [comment]
@aroth great catch! Really appreciate you calling out these edge cases. Should be fixed on v0.1.41 which is out now!
